//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weeks will be added when needed..
        /// </summary>
        internal static string Program_ChooseWeek_ {
            get {
                return ResourceManager.GetString("Program_ChooseWeek_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it. Press any key to return.
        /// </summary>
        internal static string WeekOne_ReturnToPreviousMenu_ {
            get {
                return ResourceManager.GetString("WeekOne_ReturnToPreviousMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment 2 - String Interpolation.There was also an assignment about debugging arguments, but I can&apos;t showcase that here.
        ///.
        /// </summary>
        internal static string WeekOne_Task2_ {
            get {
                return ResourceManager.GetString("WeekOne_Task2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it. Press any key to return.
        /// </summary>
        internal static string WeekTwo_ReturnToPreviousMenu_ {
            get {
                return ResourceManager.GetString("WeekTwo_ReturnToPreviousMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment 7 - Debugging.
        ///			The code provided for this assignment is the same as in WeekOne, Task 4.
        ///			It was about teaching us debugging in Visual Studio. 
        ///			Breakpoints, step-into, step-over and step-out. 
        ///			There isn&apos;t alot to show here. But feel free to: 
        ///
        ///			Type in some letters and the code will count the amount of each one....
        /// </summary>
        internal static string WeekTwo_Task1_ {
            get {
                return ResourceManager.GetString("WeekTwo_Task1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to get the next shape...
        ///.
        /// </summary>
        internal static string WeekTwo_Task2_Next {
            get {
                return ResourceManager.GetString("WeekTwo_Task2_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to view the next puzzle....
        /// </summary>
        internal static string WeekTwo_Task2_NextPuzzle {
            get {
                return ResourceManager.GetString("WeekTwo_Task2_NextPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Press any key to view the next puzzle....
        /// </summary>
        internal static string WeekTwo_Task3_Next {
            get {
                return ResourceManager.GetString("WeekTwo_Task3_Next", resourceCulture);
            }
        }
    }
}
